# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cloudmind7
email: cloudmind7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  “달의
  산 너머에,
  저 아래 그림자의 골짜기에,
  달려가요, 대담하게 달려가요.”
  그늘은 대답했다,-
  “당신이 엘도라도를 찾으신다면!”
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cloudmind7.github.io" # the base hostname & protocol for your site
twitter_username: cloudmind7
github_username:  cloudmind7

# Build settings
markdown: kramdown
